version: "3.8"

services:

    db:
        image: natohutch/floodaware
        restart: always
        environment:
            POSTGRES_PASSWORD: 1234

        volumes:
            - ./postgresdata:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        restart: always
        ports:
            - 5050:80
        environment:
            PGADMIN_DEFAULT_EMAIL: toadestra@gmail.com
            PGADMIN_DEFAULT_PASSWORD: 1234
    
    gama:
        image: gamaplatform/gama
        profiles: ["model"]